# Семинар 3

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int32')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [11]:
vec.shape

(3, 2)

Число осей:

In [12]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [13]:
np.sum(vec)

21

In [14]:
np.sum(vec, axis=0)

array([ 9, 12])

In [15]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [16]:
vec.sum()

21

Транспонируем массив:

In [17]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [18]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [19]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [20]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [23]:
vec[:, 1]

array([2, 4, 6])

In [24]:
vec[2, :]

array([5, 6])

In [25]:
vec[1:2, 0]

array([3])

In [26]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [27]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [34]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [35]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [46]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [48]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [49]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [50]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [51]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [52]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [53]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [54]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [73]:
vec.dot(vec ** 2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [76]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [77]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [78]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [80]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [81]:
np.random.rand(2, 3)

array([[0.13815193, 0.01010909, 0.32714984],
       [0.98204906, 0.24936234, 0.14592157]])

In [82]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [83]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [84]:
np.random.normal(2, 1, size=3)

array([2.0169049 , 1.48501648, 2.24450929])

In [85]:
np.random.randint(5, 10, size=3)

array([8, 6, 8])

Почему вообще используют `numpy`?

In [86]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [87]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

Wall time: 39.5 s


In [88]:
%%time
C = A @ B

Wall time: 521 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [7]:
# ┌(▼▼メ)┘ └(メ▼▼)┐

## №1

In [8]:
array = np.linspace(0,1,10)
array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [10]:
array_inverse = array[::-1]
array_inverse

array([1.        , 0.88888889, 0.77777778, 0.66666667, 0.55555556,
       0.44444444, 0.33333333, 0.22222222, 0.11111111, 0.        ])

## №2

In [41]:
array = np.random.randint(1,10,size = 10)
array

array([3, 1, 1, 8, 4, 5, 3, 3, 7, 7])

In [45]:
max_element = np.max(array[array % 2 == 1])
max_element

7

## №3

In [55]:
array = np.random.randint(0,10,size = 15)
array

array([1, 7, 7, 5, 0, 3, 5, 5, 9, 6, 2, 3, 7, 7, 8])

In [58]:
array[array%2 == 1] = 100
array

array([100, 100, 100, 100,   0, 100, 100, 100, 100,   6,   2, 100, 100,
       100,   8])

## №4

In [60]:
n = 5
array = np.arange(2*n - 1, 0, -2)
array

array([9, 7, 5, 3, 1])

In [61]:
array = np.arange(2*n)[::-2]
array

array([9, 7, 5, 3, 1])

## №5

In [64]:
def closest_and_farthest(arr, x):
    dist = np.abs(arr - x)
    return arr[np.argmin(dist)], arr[np.argmax(dist)]

In [66]:
closest_and_farthest(np.arange(10), 1.5)

(1, 9)

## №6

In [67]:
def integral(polynom):
    return np.polyint(np.poly1d(polynom)).coef

In [69]:
arr = np.arange(4)[::-1]
arr

array([3, 2, 1, 0])

In [70]:
integral(arr)

array([0.75      , 0.66666667, 0.5       , 0.        , 0.        ])

## №7

In [71]:
def first_derivative(polynom, x):
    return np.polyder(np.poly1d(polynom))(x)

In [72]:
first_derivative(arr, 4)

161